name: tech3-cicd-basic

env:
  AZURE_WEBAPP_NAME: app-tech3-gh

on:
  push:
    branches:
      - "main"
    paths:
      - 'src/**'
      - '.github/workflows/tech3-cicd-basic.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: dotnet build
        run: dotnet build "src" --configuration Release
      - name: dotnet publish
        run: dotnet publish "src" -c Release -o artifact
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: tech3-app
          path: artifact
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: tech3-app
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
